all:
  vars:
    ansible_connection: ssh
    ansible_user: azureuser
    ansible_become: true

zookeeper:
  hosts:
    kafka0:
    kafka1:
    kafka2:
kafka_broker:
  hosts:
    kafka0:
      broker_id: 1
    kafka1:
      broker_id: 2
    kafka2:
      broker_id: 3
schema_registry:
  hosts:
    kafka0:
control_center:
  hosts:
    kafka1:
kafka_connect:
  hosts:
    kafka2:
kafka_rest:
  hosts:
    kafka2:
ksql:
  hosts:
    kafka2:
